[package]
name = "expression-eval"
version = "0.1.0"
authors = ["cmkl"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
